ci:
  # pre-commit.ci will autoamtically update hooks every month
  autoupdate_schedule: monthly

repos:
  # Autoformat: Python
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black

  # Autoformat: js, markdown, yaml
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.6
    hooks:
      - id: prettier
